c---------------------------------------
c DIM.INC : Parameters which dimension
c           arrays
c---------------------------------------

c Array dimensions
        integer atmax,icdim,maxtime,totgrp
	integer nbmax,maxchg,grpdim,a1dim,a2dim,resdim
        parameter (atmax=50000,icdim=20,maxtime=5100000,totgrp=12) 
	parameter (nbmax=125,maxchg=2000,grpdim=12000)
	parameter (a1dim=200,a2dim=75,resdim=12000)
